In [1]:

from __future__ import print_function
from keras.models import Sequential
from keras.layers import Dense
from keras.models import model_from_json 
# serialize model to JSON
import os

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
                                


Using TensorFlow backend.


ModuleNotFoundError: No module named 'tensorflow'

In [11]:
 
# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")
model=loaded_model

Loaded model from disk


In [12]:
import os
ls1=os.listdir('color')
dic1={}
import scipy.misc as sm
import numpy as np
count=0
for idx,i in enumerate(ls1):
    dic1[i]=idx
    ls2=os.listdir('color/'+i)
    for j in ls2:
        #im1=np.asarray(sm.imread('color/'+i+'/'+j))
        #temp=np.zeros((len(im1),len(im1[0]),len(im1[0][0])   ))
        count=count+1
        
    
dic2={}
for i in dic1:
    dic2[dic1[i]]=i

In [16]:
def test_it():
    xvap=os.listdir('I_want_to_test_it/')
    for i in xvap:
        im1=np.asarray(sm.imread('I_want_to_test_it/'+i))
        im1=im1/255.0
        im1=im1.reshape((1,im1.shape[0],im1.shape[1],im1.shape[2]))
        print(model.predict(im1))
        xx=(np.argmax(model.predict(im1)))
        print (dic2[int(xx)])
        os.rename('I_want_to_test_it/'+i,'I_want_to_test_it/'+dic2[int(xx)]+i)
     

In [18]:
test_it()

[[  2.33745059e-08   2.26705856e-06   1.16799289e-04   9.99880910e-01]]
Apple___Black_rot
[[  3.55992051e-06   5.67668685e-05   1.02456615e-04   9.99837160e-01]]
Apple___Black_rot
[[  8.26712858e-06   4.48252795e-05   4.59050847e-04   9.99487877e-01]]
Apple___Black_rot
[[  1.32970129e-07   2.85910392e-06   4.22814861e-03   9.95768905e-01]]
Apple___Black_rot
[[  9.75254721e-09   2.97996121e-05   1.38777727e-03   9.98582482e-01]]
Apple___Black_rot
[[  4.93332557e-08   1.15092837e-06   1.69023289e-04   9.99829769e-01]]
Apple___Black_rot
[[  3.50003489e-07   4.94567903e-05   3.69386602e-04   9.99580801e-01]]
Apple___Black_rot
[[  2.16038991e-08   7.02677880e-06   2.51705264e-04   9.99741256e-01]]
Apple___Black_rot
[[  2.01643252e-06   8.32329621e-04   1.93258616e-04   9.98972416e-01]]
Apple___Black_rot
